server:
  port: 23333
  ssl:
    # 生成密钥
    # keytool -genkeypair -alias key -keypass 123456 -keyalg RSA -keysize 1024 -validity 365 -keystore ./key.jks -storepass 123456
    enabled: true
    key-store: key.jks
    key-store-password: 123456
    key-password: 123456
    key-store-type: JKS

spring:
  # spring.application.name在bootstrap中定义
  #application:
  #  name: access-gateway  # 服务名称

  #main:
  #  allow-bean-definition-overriding: true
  #  web-application-type: reactive

  web:
    resources:
      static-locations: file:../vue-rtc/dist/

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true  # 使用小写服务名，默认是大写
      routes:
        - id: access-auth
          uri: lb://access-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

      # 跨域访问
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
            max-age: 36000

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8500/rsa/publicKey #配置RSA的公钥访问地址

auth:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/auth/oauth/token"