server:
  port: 23333
  ssl:
    # 生成密钥
    # keytool -genkeypair -alias key -keypass 123456 -keyalg RSA -keysize 1024 -validity 365 -keystore ./key.jks -storepass 123456
    enabled: true
    key-store: key.jks
    key-store-password: 123456
    key-password: 123456
    key-store-type: JKS

spring:
  # spring.application.name在bootstrap中定义
  #application:
  #  # 服务名称
  #  name: access-gateway

  #main:
  #  allow-bean-definition-overriding: true
  #  web-application-type: reactive

  web:
    resources:
      static-locations: file:../vue-rtc/dist/

  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名，默认是大写
          lower-case-service-id: true
      routes:
        - id: access-auth
          uri: lb://access-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: access-admin
          uri: lb://access-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

      # 跨域访问
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
            max-age: 36000

  security:
    oauth2:
      resourceserver:
        jwt:
          #配置RSA的公钥访问地址
          jwk-set-uri: http://localhost:8500/rsa/publicKey

auth:
  ignore:
    # 配置白名单url路径
    urls:
      - /
      - /*/*.html
      - /*/*.css
      - /*/*.js
      - /*/*.ico
      - /*/*.png
      - /*/*.gif
      - /*/*.svg
      - /*/*.woff
      - /*/*.woff2
      - /*/*.ttf
      - /*/*.json
      - /doc.html
      - /webjars/**
      - /swagger-resources
      - /*/v2/api-docs
      - /auth/oauth/token
      - /auth/oauth/check_token
      - /service-message/ws