server:
  port: 23333
  ssl:
    # 生成密钥
    # keytool -genkeypair -alias tomcat_https -keypass 123456 -keyalg RSA -keysize 1024 -validity 365 -keystore ./tomcat_https.keystore -storepass 123456
    enabled: true
    key-store: tomcat_https.keystore
    key-store-password: 123456
    key-password: 123456
    key-store-type: JKS

spring:
  # application.name 在 bootstrap 中定义
  #application:
  #  # 服务名称
  #  name: access-gateway
  web:
    resources:
      static-locations: file:../vue-rtc/dist/

  gateway:
    discovery:
      locator:
        enabled: true  # 开启从注册中心动态创建路由的功能
        lower-case-service-id: true  # 使用小写服务名，默认是大写
    #routes:
    #  - id: demo1
    #    uri: lb://demo1
    #    predicates:
    #      - Path=/demo1/**

    # 跨域访问
    globalcors:
      add-to-simple-url-handler-mapping: true
      cors-configurations:
        '[/**]':
          allowedHeaders: "*"
          allowedOrigins: "*"
          allowedMethods: "*"
          max-age: 36000
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive


