server:
  port: 8501

spring:
  # spring.application.name在bootstrap中定义
  #application:
  #  # 服务名称
  #  name: access-auth

  jpa:
    database: mysql
    # 是否开启自动
    generate-ddl: false
    # 是否开启sql日志显示
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  # 数据库配置从配置中心获取
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/access-auth
    username: username
    password: password

  # redis配置从配置中心获取
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: password

