server:
  port: 8500

spring:
  # spring.application.name在bootstrap中定义
  #application:
  #  name: access-auth  # 服务名称

  # redis配置从配置中心获取
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: password

auth:
  oauth2:
    client-id: client-id
    client-secret: client-secret
    scope: all
    authorized-grant-types: client_credentials, password, implicit, authorization_code, refresh_token
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 86400
  jwt:
    key-path: key.jks
    key-alias: key
    key-password: 123456