server:
  port: 8500

spring:
  # spring.application.name在bootstrap中定义
  #application:
  #  name: access-auth  # 服务名称

  # 无需数据库连接，user数据调用admin微服务
  # 数据库配置从配置中心获取
  #datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://127.0.0.1:3306/access-auth
  #  username: username
  #  password: password

  # redis配置从配置中心获取
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: password

# 自定义auth配置
auth:
  oauth2:
    client-id: client-id
    client-secret: client-secret
    scopes:
      - all
    authorized-grant-types:
      - client_credentials
      - password
      - implicit
      - authorization_code
      - refresh_token
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 86400
  jwt:
    key-path: key.jks
    key-alias: key
    key-password: 123456

# 自定义feign配置
feign:
  name:
    access-gateway-service: access-gateway
    access-auth-service: ${spring.application.name}
    access-admin-service: access-admin
