server:
  port: 23000

spring:
  # spring.application.name在bootstrap中定义
  #application:
  #  name: service-rtc  # 服务名称

  jpa:
    show-sql: true
    #generate-ddl: false
    #hibernate:
    #  ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  # 数据库配置从配置中心获取
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-rtc
    username: username
    password: password

# 自定义feign配置
feign:
  name:
    access-gateway-service: access-gateway
    access-auth-service: access-auth
    access-admin-service: access-admin

srs:
  server-addr: 127.0.0.1:1985
